
-- Tenants Table
CREATE TABLE tenants (
    tenant_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) DEFAULT 'active',
    PRIMARY KEY (tenant_id)
);

-- Roles Table
CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    PRIMARY KEY (role_id)
);

-- Permissions Table
CREATE TABLE permissions (
    permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(255),
    PRIMARY KEY (permission_id)
);

-- Role-Permissions Junction Table
CREATE TABLE role_permissions (
    role_id NUMBER,
    permission_id NUMBER,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(permission_id) ON DELETE CASCADE
);

-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tenant_id NUMBER NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(255),
    reset_password_token VARCHAR2(255),
    reset_password_expires TIMESTAMP,
    PRIMARY KEY (user_id),
    FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    UNIQUE (tenant_id, email)
);

-- User-Roles Junction Table
CREATE TABLE user_roles (
    user_id NUMBER,
    role_id NUMBER,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE
);

-- Refresh Tokens Table
CREATE TABLE refresh_tokens (
    token_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    token VARCHAR2(500) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    PRIMARY KEY (token_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

